export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER='SET_CURRENT_USER';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_CURRENT_PROFILE = 'GET_CURRENT_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';